# Generated by Django 5.2 on 2025-05-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_resume_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
