# Generated by Django 5.2 on 2025-05-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_description',
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
