# Generated by Django 5.2 on 2025-05-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0005_remove_resume_job_description_delete_jobdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('score', models.FloatField()),
                ('job_role', models.CharField(max_length=100)),
                ('matched_skills', models.TextField()),
                ('missing_skills', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
