# Generated by Django 5.2 on 2025-05-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_jobdescription_resume_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_description',
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
