# Generated by Django 5.0.6 on 2025-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_resume_ats_score_resume_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
