# Generated by Django 5.0.6 on 2025-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_resume_address_resume_ats_score_resume_job_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='address',
        ),
        migrations.AddField(
            model_name='resume',
            name='phone_no',
            field=models.TextField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
    ]
