# Generated by Django 5.0.6 on 2025-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_resume_address_resume_name_resume_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
    ]
